import { ethers } from 'hardhat';
import fs from 'fs';
import path from 'path';

async function main() {
  const Stake = await ethers.getContractFactory('MeeStake');
  const stake = await Stake.deploy();
  await stake.waitForDeployment();

  const address = await stake.getAddress();
  console.log('MeeStake deployed at:', address);

  // 1) เขียน .env.local สำหรับ Vite (VITE_ prefix จะถูกเข้าถึงได้ใน runtime)
  const envLocalPath = path.resolve(process.cwd(), '.env.local');
  const envLocalContent = `VITE_CONTRACT_ADDRESS=${address}
VITE_RPC_URL=${process.env.ETH_RPC_URL ?? 'http://localhost:8545'}
`;
  fs.writeFileSync(envLocalPath, envLocalContent, { encoding: 'utf8' });
  console.log(`Wrote .env.local -> ${envLocalPath}`);

  // 2) เขียน src/config.ts เพื่อให้โค้ด TypeScript สามารถ import ใน runtime/dev ได้โดยตรง
  const configTsPath = path.resolve(process.cwd(), 'src', 'config.ts');
  const configTsContent = `// Auto-generated by deploy.ts
export const CONTRACT_ADDRESS = "${address}";
export const RPC_URL = "${process.env.ETH_RPC_URL ?? 'http://localhost:8545'}";
`;
  // Ensure src directory exists (should exist in your project)
  fs.writeFileSync(configTsPath, configTsContent, { encoding: 'utf8' });
  console.log(`Wrote src/config.ts -> ${configTsPath}`);

  console.log('Deployment artifacts written. You can now run pnpm dev and the app will import the deployed contract address from src/config.ts or VITE_CONTRACT_ADDRESS.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
